### ISSUE TITLE
Spaces admins can't add images in WYSIWYG editors

### ISSUE THREAD

**Issue by paulinebessoles** [Platoniq/decidim-module-decidim_awesome#112]
**Describe the bug**
As a space admin, when trying to upload an image into a WYSIWYG editor (thanks to Decidim awesome), the image never loads in the field. 

**To reproduce**
1. Add a space admin test user
2. Enable images in the rich text editor in Decidim Awesome
2. Logged with this space admin, try to add an image on a rich text editor. 
3. See error

**Screenshots**
_When logged as an admin, the image loads normally_

<img width="1440" alt="Capture d’écran 2021-06-23 à 18 08 14" src="https://user-images.githubusercontent.com/52420208/123132368-f6516880-d44e-11eb-9e1c-324551a59beb.png">

_When logged as a space admin, the image never loads, although the editor try to load_

<img width="1440" alt="Capture d’écran 2021-06-23 à 18 08 23" src="https://user-images.githubusercontent.com/52420208/123132373-f94c5900-d44e-11eb-8631-6bd98ba58c48.png">

**Comment by microstudi** [comment]
Regarding this, we will need to check the implications of the inclusion of this feature in the main Decidim code. Code was ported by @entantoencuanto in https://github.com/decidim/decidim/pull/8250.

**Comment by paarals** [comment]
we have identified the error, as @paulinebessoles said. in the coming days we will have it fixed.

the problem comes when we enable rich text in the custom proposal.

- if you are an administrator, you can easily add the image
- if you are not an administrator, you will not be able to add the image
