### ISSUE TITLE
Add Japanese as target language in Crowdin

### ISSUE THREAD

**Issue by takahashim** [Platoniq/decidim-module-decidim_awesome#119]
I'm trying to use this module in our Decidim instance in Japanese, but there is no Japanese locale file in this module.
We are currently adding our own YAML file, but it would be great if we could add/update it via Crowdin.
Could you please add Japanese as a target language to the Crowdin project?

Thanks in advance,

**Comment by microstudi** [comment]
Sure! you got it! thanks a lot @takahashim for your contribution! let me know if you want me to add japanese to any other plugin we've got

**Comment by takahashim** [comment]
Thank you for your quick response!  I've filled out the translation of JA locale.
I will contact again if we have other plugins that we would like to use.
