### ISSUE TITLE
Bug Menu Tweaks

### ISSUE THREAD

**Issue by OuardaOUBAHRI** [Platoniq/decidim-module-decidim_awesome#124]
## **Describe the bug**

As an admin:  

1. I created a participatory process and added it to the menu with Decidim Awesome/Tweaks de menu
2. I created an assembly and added it to the menu with Decidim Awesome/Tweaks de menu

![image](https://user-images.githubusercontent.com/76660393/133392162-610da8a0-2a8b-47fd-8519-f8ca25d0b45a.png)

The bug appears when I try to navigate :

- from the participatory process tab in the navbar to the assemblie tab (see it [here](https://participez-tours.dcd-commercial-sbox.osp.dev/))
- from the assembly tab to the process tab (sign in and see it [here](https://decidim-app-test.opensourcepolitics.net/) ).

⚠️ In both cases, the page is accessible from the other tabs.

A wrong url is generated ("processes" or "assemblies" is added to correct url) : 

![image](https://user-images.githubusercontent.com/76660393/133392268-d94e194b-419d-4dba-8078-3562494fd317.png)

Should be 

![image](https://user-images.githubusercontent.com/76660393/133392329-6b128bb2-ae1f-483b-94a5-db3b649d530b.png)

## **To Reproduce**

*Steps to reproduce the behavior:*
Case 1: 
1. Go to [https://participez-tours.dcd-commercial-sbox.osp.dev/processes/BudgetParticipatif](https://participez-tours.dcd-commercial-sbox.osp.dev/processes/BudgetParticipatif)
2. Click on 'Rencontres Citoyennes'
3. See error

Case 2: 
1. Go to [https://decidim-app-test.opensourcepolitics.net/assemblies/TestAssemblie](https://decidim-app-test.opensourcepolitics.net/assemblies/TestAssemblie)
2. Click on 'Test Concertation'
3. See error

## **Expected behavior**

I should be able to navigate between all the navigation items. 

## **Screenshots**

![image](https://user-images.githubusercontent.com/76660393/133392412-98f84600-e7ed-4620-9d1f-6eae59bc6f76.png)

Navigate from "Budget Participatif " to "Rencontres Citoyennes"

![image](https://user-images.githubusercontent.com/76660393/133392501-67b76358-9a42-4585-abc3-78e5da79f958.png)

[decidim test -app](https://decidim-app-test.opensourcepolitics.net/)  : Navigate from "Test Assemblie" to "Test Concertation"

**Comment by microstudi** [comment]
Hi @OuardaOUBAHRI please take a look at your "path" definition in you menu, you are using relative URL's, like this:

`assemblies/RencontresCitoyennes`

 that's why you get this strange behaviour. Try to use this path instead (note the `/` at the beggining):

`/assemblies/RencontresCitoyennes`

**Comment by OuardaOUBAHRI** [comment]
Hello @microstudi, 
indeed, that was the problem. thank you !
