### ISSUE TITLE
Custom Styles : rename label doesn't work

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-decidim_awesome#132]
When trying to change the label of a CSS box, changes are not displayed after updating configuration. Tested on https://facilitation.platoniq.net/ : 

https://user-images.githubusercontent.com/72607737/136033082-ed6bedb4-ce31-4cf2-878d-2f6a7eea45e6.mov

**Comment by microstudi** [comment]
@marta-platoniq Thanks Marta, great as always!

if the page is renewed without saving, does the new label appear?

**Comment by marta-platoniq** [comment]
@microstudi Yes, when I rename a label and refresh the page without saving, it works fine. However, when I click "update configuration" after renaming a label, it is not changed and (this is new) restrictions are lost.

**Comment by microstudi** [comment]
@marta-platoniq noted! and fix on the way, thanks!

**Comment by microstudi** [comment]
This should be fixed now (decidim-demo updated).

**Comment by marta-platoniq** [comment]
Yes, fixed :)
