### ISSUE TITLE
[custom-fields] Incorrect validation on radio-button and checkbox when they are required fields

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-decidim_awesome#133]
NOTE: this bug only happens when the fields are required.

**BUG DESCRIPTION**
CHECKBOX:
I have a checkbox group that is a required field. 
When editing a proposal or at the completion step of a proposal creation (step 3), I get a validation error (Minium 1 selections required) although there are some options selected. 

RADIO-BUTTON:
When the field is required and I select the "other" option, if I don't fill out the input box no error is given. But if I fill out the "other" input box, I get an error and the form goes a little crazy.

**HOW TO REPRODUCE**
Create a new proposal and check both errors here (for radio-button, select the "other" option):

[https://demo.platoniq.net/processes/awesome/f/154/](https://demo.platoniq.net/processes/awesome/f/154/)
USER: facilita@platoniq.net
PASSWORD: 4wesome-decidim

**Comment by microstudi** [comment]
Tambe hauria d'estar resolt a demo
