### ISSUE TITLE
Awesome map doesn't display any place

### ISSUE THREAD

**Issue by PierreMesure** [Platoniq/decidim-module-decidim_awesome#144]
Hi,

Thanks a lot for the plugin, we use many of its features regularly.

I recently updated some of our platforms to the Decidim 0.24.3 and Decidim-Awesome to 0.7.2.

Unfortunately, the Awesome Map component stops working as soon as there are too many pins in one of my components, it's not displaying any of the pins anymore, although the legend still lists the Proposals and Meetings components.

Here's a link to [one of the platforms](https://hgf.demokratiskastader.se/processes/hjallbo/f/4/).

I tried to reproduce the GraphQL query that is used to retrieve the proposals and I'm getting the following error message (reproduce [here](https://hgf.demokratiskastader.se/api/graphiql?query=%7B%0A%20%20component(id%3A%208)%20%0A%20%20%7B%0A%20%20%20%20id%0A%20%20%20%20__typename%0A%20%20%20%20...%20on%20Proposals%20%7B%0A%20%20%20%20%20%20proposals(first%3A%2050%2C%20after%3A%20%22%22)%7B%0A%20%20%20%20%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20state%0A%20%20%20%20%20%20%20%20%20%20%20%20title%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20translations%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20locale%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20body%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20translations%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20locale%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20address%0A%20%20%20%20%20%20%20%20%20%20%20%20coordinates%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20latitude%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20longitude%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20amendments%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20emendation%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20category%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%20%20)):
`Query has complexity of 1057, which exceeds max complexity of 300`

I don't get the same error message if I reduce the query size to 5 or 10 so it seems to be a problem of scalability with the API or the query.

**Comment by PierreMesure** [comment]
I managed to fix it by increasing the max_complexity of the API.

**Comment by PierreMesure** [comment]
Maybe an improvement could be to add an error message somewhere? Or to document it?

**Comment by microstudi** [comment]
Mmm, If you don't mind, I'll keep this issue open as, ideally, the awesome map should work with the Decidim defaults. Probably there's a way to fix this within awesome. Let's leave it opened for a future fix
