### ISSUE TITLE
Awesome map's custom height doesn't work

### ISSUE THREAD

**Issue by PierreMesure** [Platoniq/decidim-module-decidim_awesome#145]
The problem is happening [here](https://hgf.demokratiskastader.se/processes/hjallbo/f/4/).

The map's height is 450px, despite it being set to another value in the component's settings.

Something seems to be overriding the value and I believe it's this [line](https://github.com/decidim/decidim/blob/b85398065958c4d01739160ea94d9a867850503d/decidim-core/app/assets/stylesheets/decidim/modules/_map.scss#L7).

**Comment by microstudi** [comment]
Good catch, the error is here though:
https://github.com/Platoniq/decidim-module-decidim_awesome/blob/93deb8eceaa5e4930b9faca4e61b763ac086da0c/app/views/decidim/decidim_awesome/map_component/map/show.html.erb#L58

Initially the awesome map had the id `#map`, is `#awesome-map` now, so it is a easy fix. Will be fixed next release. 
Thanks for reporting
