### ISSUE TITLE
Awesome map's filtering menu doesn't filter correctly

### ISSUE THREAD

**Issue by PierreMesure** [Platoniq/decidim-module-decidim_awesome#146]
The problem is happening [here](https://hgf.demokratiskastader.se/processes/hjallbo/f/4/?locale=en).

The pins on the map come from different Proposals components and they all have different categories. Because of the latter, they are shown with different colors on the map.

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/7223028/146044017-6117fdc0-777b-41a7-bf5a-f1b16f0e2ac8.png">

But when trying to filter them by component, no change is noticeable when unticking the boxes, except the last one that hides/shows them all.

**Comment by microstudi** [comment]
Looks like there's a bunch of javascript errors. We will try to reproduce it locally and see if we can spot the problem
