### ISSUE TITLE
Shorter URLs feature

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-decidim_awesome#156]
It would be interesting to shorten some non-so-friendly URLs within Decidim.

An example:

I want to share a form with the following URL: [https://smiles.platoniq.net/processes/training/f/181/](https://smiles.platoniq.net/processes/training/f/181/)

Wouldn't it be more awesome to share a shorter URL like [https://smiles.platoniq.net/interest-form](https://smiles.platoniq.net/interest-form) that redirects to [https://smiles.platoniq.net/processes/training/f/181/](https://smiles.platoniq.net/processes/training/f/181/)?

To keep in mind (by our awesome genius @microstudi):
- take current URLs into account, like "/processes". Only redirect if there is nothing in the shortened URL.

**Comment by larsUE** [comment]
Hi Marta! Just so that you don't start developing something from scratch: OSP's Module [URL Aliases](https://github.com/OpenSourcePolitics/decidim-urlaliases) does precisely that.

**Comment by microstudi** [comment]
Although that module is handy, we are going to implement this feature anyway as this plugin already handles redirections for another use case (scoped admins).
With this implementation no additional migrations or new gems are required, and we will allow full url redirections as well
