### ISSUE TITLE
Announcement in Fullscreen iframes

### ISSUE THREAD

**Issue by PierreMesure** [Platoniq/decidim-module-decidim_awesome#39]
I tried the fullscreen iframe function for the first time a few weeks ago and I love it! Thank you so much!

For a future improvement, I suggest to allow to write an announcement, just as it is possible for other components. I guess it could be implemented in the same way, with one general announcement and the possibility of setting specific announcements for every step.

This is especially useful as you don't always have control over the content of the iframe. Being able to add a short message above it would be really useful.

**Comment by microstudi** [comment]
good idea, in fact I'm not really sure why I didn't! to the backlog...

**Comment by microstudi** [comment]
implemented via #43

**Comment by PierreMesure** [comment]
🥳
