### ISSUE TITLE
The asset "decidim/decidim_awesome/application.css" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by BigSnicker** [Platoniq/decidim-module-decidim_awesome#46]
Did a simple install with the three bundle instructions.  On reboot, we got:

"500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong."

And the nginx log produces this:

[ N 2021-01-27 01:03:06.9897 767/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-01-27 01:03:07.5774 837/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-01-27 01:03:07.5854 837/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-01-27 01:03:07.7015 837/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 837
[ N 2021-01-27 01:03:10.3213 837/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 1368 output: Error during failsafe response: The asset "decidim/decidim_awesome/application.css" is not present in the asset pipeline.
App 1368 output:
App 1368 output:   /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:84:in `compute_asset_path'
App 1368 output:   /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.4/lib/action_view/helpers/asset_url_helper.rb:200:in `asset_path'
App 1368 output:   /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.4/lib/action_view/helpers/asset_url_helper.rb:345:in `stylesheet_path'
App 1368 output:   /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.4/lib/action_view/helpers/asset_tag_helper.rb:143:in `block in stylesheet_link_tag'
App 1368 output:   /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.4/lib/action_view/helpers/asset_tag_helper.rb:142:in `map'
App 1368 output:   /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionview-5.2.4.4/lib/action_view/helpers/asset_tag_helper.rb:142:in `stylesheet_link_tag'
App 1368 output:   /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:186:in `block in stylesheet_link_tag'
App 1368 output:   /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:184:in `map'
App 1368 output:   /home/decidim/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:184:in `stylesheet_link_tag'

**Comment by microstudi** [comment]
Hi @BigSnicker , did you precompile your assets after installation, also, can you show your Gemfile?

**Comment by BigSnicker** [comment]
I noticed application.css isn't in assets/stylesheets in the repository.  Is that normal?

**Comment by BigSnicker** [comment]
You are correct, I didn't precompile!

RAILS_ENV=production bundle exec rake assets:precompile, for any other newbies who read this.

Works great now.
