### ISSUE TITLE
Menu tweaks: menu does not underline active item, but "Home" (or "Processes")

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-decidim_awesome#56]
A http://demo.platoniq.net/ , vaig a "Procés Participatiu" i tot correcte, però (malditos "peros") al menú en comptes de seleccionar "Procés Participatiu" selecciona "Inici". Si tingués el tab "Processos" visible, seleccionaria "Processos", com passa amb l'item "Consell Estudiants", que selecciona "Assemblees". 

![image](https://user-images.githubusercontent.com/72607737/108838897-94820e80-75d4-11eb-87ee-3526a02edb2a.png)

**Comment by marta-platoniq** [comment]
El primer cas és el test d'un hack que necessitem pel decidim d la UOC: https://github.com/Platoniq/decidim-uoc/issues/10

**Comment by microstudi** [comment]
No passaria si en comptes de posar el link sencer `http://demo.platoniq.net/processes/proces-bugs` es posa nomes la part del path `/processes/proces-bugs`.

Potser la millor solucio seria detectar si la url pertany al propi decidim i fer-ho automaticament

**Comment by marta-platoniq** [comment]
Ahhh cert! Ja funciona. Podem posar un missatget que ho indiqui? Serà super útil si indica que ha de començar per "/" ja que és la típica cosa que no recordes si has de posar o no.

**Comment by microstudi** [comment]
Casi millor detectar-ho automaticament no?
TODO:
- [ ] Detect host from a new url and remove it if matches the organization.host
- [ ] Generate url in admin without locales

**Comment by microstudi** [comment]
Fixed
