### ISSUE TITLE
[custom-fields] Checkbox group does not load selected options (neither in step 3 nor in proposal edition) when it is a required field

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-decidim_awesome#82]
**Describe the bug**
He posat un camp checkbox group. Al pas 1 selecciono alguns ítems, però en arribar al pas 3 (completa la teva proposta) no hi ha cap ítem seleccionat al checkbox group. Tampoc es seleccionen si des de la vista prèvia vaig a "Modifica la proposta" (abans de publicar la proposta), ni quan vaig a "Editar proposta" (després d'haver-la publicat).

**To Reproduce**
1. Go to [https://coincidim.cat/assemblies/impulsem/f/49/proposals/new](https://coincidim.cat/assemblies/impulsem/f/49/proposals/new)
2. Omplir els camps i seleccionar alguns ítems del checkbox
3. Al pas 3 de la selecció de propostes, els ítems seleccionats en el pas anterior, no apareixen seleccionats.
**Expected behavior**
Que es mantinguin els ítems seleccionats, tant al pas 3 de la creació de propostes com a modificar i editar propostes.

**Screenshots**

<img width="735" alt="image" src="https://user-images.githubusercontent.com/72607737/116410809-6b306980-a835-11eb-9192-de2bdc88dbb0.png">
(no tinc clar el valor que ha d'anar a la segona columna)
 

https://user-images.githubusercontent.com/72607737/116411665-37097880-a836-11eb-8841-7ac652e4fbbc.mov

**Comment by marta-platoniq** [comment]
bug fixed 🤩. Thanks!

**Comment by Kagemaru** [comment]
We are still encountering this bug.
Note that it only occurs if checkboxes are marked as required.

I assume that the error happens somewhere around [here in the source for formBuilder](https://github.com/kevinchappell/formBuilder/blob/902206505760b8af8417f479a4ddcdc641c46b10/src/js/control/select.js#L36)

My Javascript-Fu is not good enough to fix it there, but I've wrote a hotfix to get it to work in decidim_awesome.

In custom_fields.js.es6#89:
```javascript
    /*
     Hack to fix required checkboxes being reset
     The problem probably exists somewhere around here:
     https://github.com/kevinchappell/formBuilder/blob/902206505760b8af8417f479a4ddcdc641c46b10/src/js/control/select.js#L36
    */
    $('.formbuilder-checkbox-group').each(function (_key, group) {
      const inputs = $('.formbuilder-checkbox input', group);
      var values = inputs.attr('user-data').split(' ');

      inputs.each(function (_key, input) {
        var index = values.indexOf(input.value);
        if (index >= 0) {
          input.checked = true;
          delete values[index];
        } else {
          input.checked = false;
        }
      });

      // Fill "other" option
      const other_option = $('.other-option', inputs.parent())[0]
      const other_val = $('.other-val', inputs.parent())[0]
      const other_text = values.filter(Boolean)[0]

      if (other_option) {
        if (other_text) {
          other_option.checked = true;
          other_val.value = other_text;
        } else {
          other_option.checked = false;
          other_val.value = '';
        }
      }
    });
```

**Comment by carlobeltrame** [comment]
I think this has also been reported in formBuilder in this issue: https://github.com/kevinchappell/formBuilder/issues/910

There are some workarounds listed by other users, but they are also quite hacky...

**Comment by microstudi** [comment]
I see, feel free to create a PR with this hack (put a comment to link the original issue in formBuilder so we will update when solved).
Thanks @carlobeltrame

**Comment by Kagemaru** [comment]
> 
> 
> I think this has also been reported in formBuilder in this issue: [kevinchappell/formBuilder#910](https://github.com/kevinchappell/formBuilder/issues/910)
> 
> There are some workarounds listed by other users, but they are also quite hacky...

I've seen a few of them in different issues. My solution actually grew out of them, because somehow none of them did exactly what I wanted, which is setting the checked state for the predetermined checkboxes but also keep the checked state/text value of the "other" checkbox. 

I will prepare the PR today.

**Comment by marta-platoniq** [comment]
The fix is not working for me. 
I've filled out all the fields in step 1, but when I click "Continue" I get an error as if no data was completed.


https://user-images.githubusercontent.com/72607737/122424645-2e5c3580-cf8f-11eb-8ab3-4b61a0695a9e.mov

**Comment by Kagemaru** [comment]
Sorry, an attribute access error snuck in during the creation of the PR.
I've fixed it and created a new PR: https://github.com/Platoniq/decidim-module-decidim_awesome/pull/106

Also the "other" checkbox should correctly keep it's value now.

**Comment by marta-platoniq** [comment]
Hi! Thanks for the fix :) Now I have a problem with the (javascript?) validation in step 3: 

https://user-images.githubusercontent.com/72607737/122748255-4502d500-d28c-11eb-9e14-0be6fcc61ecb.mov

**Comment by marta-platoniq** [comment]
Issue has been fixed, but there is still a problem with javascript(?) validation when creating a proposal (step 3) and when editing it. 
Related to #133 .
