### ISSUE TITLE
[custom-fields] Special chars are not loaded correctly (mat&#xED; instead of matí)

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-decidim_awesome#83]
**Describe the bug** 
Les lletres accentuades dins d'un text field o text area no es carreguen bé, ni al step 3, ni a modificar proposta ni a editar-la. 
 
**To Reproduce** 
1. Go to https://coincidim.cat/assemblies/impulsem/f/49/proposals/new 
2. Omplir els camps i a horari posar, per exemple, "Matí"
3. Al pas 3 de la selecció de propostes, en comptes de "Matí" surt `"Mat&#xED;"`. 

**Expected behavior** 
Mantenir els accents i no ofendre a l'SCA (Special Characters Association). 
 
**Screenshots**
<img width="946" alt="image" src="https://user-images.githubusercontent.com/72607737/116414439-c152dc00-a838-11eb-94e0-1e3a122520eb.png">

**Comment by microstudi** [comment]
@marta-platoniq can you check if this is solved, it is deployed in coincidim.

**Comment by marta-platoniq** [comment]
This issue has been solved partially. From step 3 (complete the proposal) to step 4, special chars are loaded correctly :) buuuut I lose all the content information introduced at step 1 when moving on to the next step (as it happens here https://github.com/Platoniq/decidim-module-decidim_awesome/issues/82 with checkbox group, but now it happens with all  fields).

https://user-images.githubusercontent.com/72607737/120790633-7dd44780-c533-11eb-8d7a-2a4ab52febcc.mov

**Comment by microstudi** [comment]
ok, nice debugging

**Comment by larsUE** [comment]
Hello! We believe the loss of information had to do with https://github.com/Platoniq/decidim-module-decidim_awesome/issues/88
-> we've fixed that error message and all information gets carried over :)

**Comment by microstudi** [comment]
#88 fix is merged, let's try again!

**Comment by marta-platoniq** [comment]
@microstudi has fet update a Coincidim, @ivanverges ? (he provat i segueix fallant 🐞)

**Comment by marta-platoniq** [comment]
Fixed 🥳  thanks!!
