### ISSUE TITLE
[custom-fields] Doubt about maximum proposal body length setting

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-decidim_awesome#85]
Com gestionem la longitud màxima del cos de la proposta amb els custom fields?

Per defecte, quan crees un component propostes el cos té una longitud màxima de 500 caràcters, xifra a la qual és molt fàcil arribar-hi amb els custom fields, i l'error que dona és bastant il·lògic per la usuària:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/72607737/116426953-ded97300-a843-11eb-984d-01939b1cc4c1.png">

Per evitar que surti aquest error, com ho fem?
Posem un avís al formulari de l'awesome pq l'admin ho tingui en compte i configuri la longitud del cos de la proposta a un número bastant elevat? 
Ignorem la limitació màxima de caràcters 😏 (dubto que es pugui)?

**Comment by microstudi** [comment]
@marta-platoniq s'hauria de gestionar com a bug suposo. Hauria el sistema sobreescriure aquest limit de manera automàtica?

**Comment by marta-platoniq** [comment]
No sé quines possibilitats tenim amb el Decidim, però tu que li coneixes les entranyes i les intimitats sabràs com fer la màgia 🧞‍♂️ 

Si sobreescrivim el límit, li posaríem un valor molt elevat sempre, o en funció del nombre de custom fields? Posar un valor molt elevat podria tenir conseqüències contraproduents?

**Comment by microstudi** [comment]
@marta-platoniq Simplement il·limitat diria jo. Però vaja ja hi trobarem la solució

**Comment by marta-platoniq** [comment]
He vist que es pot posar a 0 la longitud del cos de la proposta i, suposo, que vol dir que és il·limitat. Però per defecte no és 0, és 500, i si amb els custom fields ens passem, dóna error.
Posem un avís a dalt de tot de custom fields pq l'admin tingui en compte de fer aquesta modificació en la longitud del cos de la proposta?
