### ISSUE TITLE
Applicable cases filter does not consider the landing page of the process groups

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-decidim_awesome#93]
**Describe the bug**
La versió Decidim 0.24 incorpora una landing page pels grups de processos. Si hi vull aplicar, per exemple, un CSS personalitzat, no puc seleccionar un grup de processos, ja que no està considerat al filtre de casos aplicables:

![image](https://user-images.githubusercontent.com/72607737/120159717-c919ed80-c1f5-11eb-9d0c-9acbbc1eab23.png)

**To Reproduce**
- Decidim Awesome de la v0.24 > Qualsevol filtre de casos aplicables 

**Expected behavior**
Incloure "Process groups" dins d' "Apply to participatory spaces of type" (?)

**Comment by microstudi** [comment]
@marta-platoniq cal afegir tambe les questions de consultations, que es tracten com espais participatius
